spring:
  datasource:
    url: ${PHOENIX_DB_URL}
    username: ${PHOENIX_DB_USERNAME}
    password: ${PHOENIX_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

app:
  security:
    password:
      min-length: 12
      uppercase: 1
      lowercase: 1
      numbers: 1
      special: 1
      special-characters: "!@#$%^&*()_+-=[]{}"